services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: